# Generated by Django 3.2 on 2021-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0002_rename_contactus_reachus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachus',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
            preserve_default=False,
        ),
    ]
