# Generated by Django 3.2 on 2021-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0003_reachus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachus',
            name='mobile',
            field=models.CharField(max_length=150),
        ),
    ]
