# Generated by Django 3.2 on 2021-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('button_text', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/slider/%Y')),
            ],
        ),
    ]
