# Generated by Django 3.2 on 2021-04-14 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='meadia/ytuber/%Y/%m')),
                ('video_url', models.URLField(max_length=250)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('camera_type', models.CharField(max_length=150)),
                ('subs_count', models.IntegerField()),
                ('category', models.CharField(max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('crew', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
