# Generated by Django 3.2 on 2021-04-14 09:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('sony', 'sony'), ('red', 'red'), ('panasonic', 'panasonic'), ('fuji', 'fuji'), ('other', 'other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('gaming', 'gaming'), ('vlogs', 'vlogs'), ('cooking', 'cooking'), ('film_making', 'film_making'), ('comedy', 'comedy')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('medium', 'medium'), ('large', 'large')], max_length=150),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
