# Generated by Django 3.2 on 2021-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210414_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.CharField(max_length=150),
        ),
    ]
