# Generated by Django 3.2 on 2021-04-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='links',
            name='mobile',
        ),
    ]
