# Generated by Django 3.2 on 2021-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210422_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='fb_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='links',
            name='insta_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='links',
            name='yt_link',
            field=models.CharField(max_length=150),
        ),
    ]
